# Generated by Django 4.1.1 on 2022-10-26 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaspInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('individual_id', models.PositiveSmallIntegerField(unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('in_use', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='ユーザー名')),
                ('email_address', models.EmailField(max_length=254)),
                ('hash_password', models.CharField(max_length=254, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('container_image', models.CharField(max_length=30, verbose_name='画像のファイル名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.container', verbose_name='容器ID')),
            ],
        ),
        migrations.CreateModel(
            name='BottleInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ボトル名')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('bottle_volume', models.PositiveSmallIntegerField()),
                ('is_favorite', models.BooleanField(default=0, verbose_name='お気に入り')),
                ('memo', models.TextField(verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.container', verbose_name='容器ID')),
                ('rasp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.raspinformation', verbose_name='ラズパイID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.user', verbose_name='ユーザーID')),
            ],
        ),
    ]
