# Generated by Django 4.1.1 on 2022-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
