# Generated by Django 4.1.1 on 2022-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_alter_raspinformation_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspinformation',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
