# Generated by Django 4.1.1 on 2022-10-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_alter_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=100, verbose_name='メールアドレス'),
        ),
    ]
