# Generated by Django 4.1.1 on 2022-10-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_alter_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
