# Generated by Django 4.1.1 on 2022-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_alter_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottleinformation',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='容器の種類'),
        ),
        migrations.AlterField(
            model_name='raspinformation',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
