# Generated by Django 4.1.1 on 2022-11-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0009_alter_bottleinformation_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleType',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='ボトルの種類')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RasPi',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('individual_id', models.PositiveSmallIntegerField(unique=True)),
                ('mac_address', models.PositiveSmallIntegerField(unique=True)),
                ('in_use', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'RaspberryPi識別',
            },
        ),
        migrations.CreateModel(
            name='UserBottle',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ボトル名')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名')),
                ('bottle_volume', models.PositiveSmallIntegerField()),
                ('remaining_quantity', models.PositiveSmallIntegerField()),
                ('is_favorite', models.BooleanField(default=False, verbose_name='お気に入り')),
                ('memo', models.TextField(null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('bottle_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.bottletype', verbose_name='種類ID')),
            ],
            options={
                'verbose_name_plural': 'ボトル情報',
            },
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name_plural': '容器'},
        ),
        migrations.AlterModelOptions(
            name='containerimage',
            options={'verbose_name_plural': '容器画像'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'ユーザー管理'},
        ),
        migrations.DeleteModel(
            name='BottleInformation',
        ),
        migrations.DeleteModel(
            name='RaspInformation',
        ),
        migrations.AddField(
            model_name='userbottle',
            name='container_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.container', verbose_name='容器ID'),
        ),
        migrations.AddField(
            model_name='userbottle',
            name='raspi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.raspi', verbose_name='ラズパイID'),
        ),
        migrations.AddField(
            model_name='userbottle',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appapi.user', verbose_name='ユーザーID'),
        ),
    ]
