# Generated by Django 4.1.1 on 2022-11-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0010_bottletype_raspi_userbottle_alter_container_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottletype',
            options={'verbose_name_plural': 'ボトルの種類'},
        ),
        migrations.AlterField(
            model_name='raspi',
            name='mac_address',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
