# Generated by Django 4.1.3 on 2023-01-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0014_alter_userbottle_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspi',
            name='individual_id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='raspi',
            name='mac_address',
            field=models.SlugField(max_length=17),
        ),
    ]
