# Generated by Django 4.1.3 on 2023-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0015_alter_raspi_individual_id_alter_raspi_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottletype',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='containerimage',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='raspi',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userbottle',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
